import type { OseAdvancedRace } from "./class-types";

export const OSE_ADVANCED_RACES: Record<string, OseAdvancedRace> = {
  Drow: {
    abilityModifiers: { dex: 1, con: -1 },
    classes: {
      Acrobat: 10,
      Assassin: 10,
      Cleric: 11,
      Fighter: 7,
      Knight: 9,
      "Magic-User": 9,
      Thief: 11,
    },
    requirements: { int: 9 },
    languages: ["Alignment", "Common", "Elvish", "Deepcommon", "Gnomish"],
  },
  Duergar: {
    abilityModifiers: { con: 1, cha: -1 },
    requirements: { con: 9, int: 9 },
    languages: ["Alignment", "Common", "Deepcommon", "Dwarvish", "Goblin", "Kobold"],
    classes: {
      Assassin: 9,
      Cleric: 8,
      Figher: 9,
      Thief: 9,
    },
  },
  Dwarf: {
    abilityModifiers: { con: 1, cha: -1 },
    requirements: { con: 9 },
    languages: ["Alignment", "Common", "Dwarvish", "Gnomish", "Goblin", "Kobold"],
    classes: {
      Assassin: 9,
      Cleric: 8,
      Figher: 10,
      Thief: 9,
    },
  },
  Elf: {
    abilityModifiers: { dex: 1, con: -1 },
    requirements: { int: 9 },
    languages: ["Alignment", "Common", "Elvish", "Gnoll", "Hobgoblin", "Orcish"],
    classes: {
      Acrobat: 10,
      Assassin: 10,
      Cleric: 7,
      Druid: 8,
      Fighter: 7,
      Knight: 11,
      "Magic-User": 11,
      Ranger: 11,
      Thief: 11,
    },
  },
  Gnome: {
    abilityModifiers: {},
    requirements: { int: 9, con: 9 },
    languages: ["Alignment", "Common", "Dwarvish", "Gnomish", "Kobold"],
    classes: {
      Assassin: 6,
      Cleric: 7,
      Figher: 6,
      Illusionist: 7,
      Thief: 8,
    },
  },
  "Half-Elf": {
    abilityModifiers: {},
    requirements: { cha: 9, con: 9 },
    languages: ["Alignment", "Common", "Elvish"],
    classes: {
      Acrobat: 12,
      Assassin: 11,
      Bard: 12,
      Cleric: 5,
      Druid: 12,
      Figher: 8,
      Knight: 12,
      "Magic-User": 8,
      Paladin: 12,
      Ranger: 8,
      Thief: 12,
    },
  },
  Halfling: {
    abilityModifiers: { dex: 1, str: -1 },
    requirements: { dex: 9, con: 9 },
    languages: ["Alignment", "Common", "Halfling"],
    classes: {
      Druid: 6,
      Figher: 6,
      Thief: 8,
    },
  },
  "Half-Orc": {
    abilityModifiers: { cha: -2, con: 1, str: 1 },
    requirements: {},
    languages: ["Alignment", "Common", "Orcish"],
    classes: {
      Acrobat: 8,
      Assassin: 8,
      Cleric: 4,
      Fighter: 10,
      Thief: 8,
    },
  },
  Human: {
    abilityModifiers: {},
    requirements: {},
    classes: {},
    languages: ["Alignment", "Common"],
  },
  Svirfneblin: {
    abilityModifiers: {},
    requirements: { con: 9 },
    languages: ["Alignment", "Common", "Deepcommon", "Gnomish", "Dwarvish", "Kobold"],
    classes: {
      Assassin: 8,
      Cleric: 7,
      Fighter: 6,
      Illusionist: 7,
      Thief: 8,
    },
  },
};
